version: '3'
services:
  submit: 
    build: env/submit/
    command: make
    volumes:
      - .:/app/
  # solver:
  #   build:
  #     context: ./
  #     dockerfile: ./env/triton/Dockerfile
  #   command: ./solve.sh
  #   volumes:
  #     - .:/app/follow-me/solver/
  #     - ../sample/:/app/follow-me/sample/
  #     - ../trace/:/app/follow-me/trace/
  #   environment:
  #     - SHELL:/bin/bash